server:
  port: 8084
  ssl:
    enabled: false
bot:
  name: qdbp808_bot
  token: 7260433569:AAENedfV76bp_Fs4lr3us2W3ZWnIWtJP1jQ
  uri: https://9d5e-94-180-208-33.ngrok-free.app
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: userok
    password: p@ssw0rd
    queues:
      text-message-update: text_message_update
      doc-message-update: doc_message_update
      photo-message-update: photo_message_update
      answer-message: answer_message